### PR TITLE
Schemaless assets

### LINKED ISSUE #6: CSS fails to load when visiting https://urho3d.github.io
Every time I visit urho3d.github.io Firefox blocks content with the notice: "This site does not supply identity information."
I need to disable this protection for every new session for the CSS to load. In this case I'm not held back by this, but I can imagine other people are.

### PR DESCRIPTION
**Pull request by friesencr**
Modifies configuration to use root url convention or https for remote assets.

Trying to fix #6

### CODE REVIEW

**Comment by weitjong** [comment]
Thanks for the PR. I will investigate whether github pages now supports https protocol and see if it indeed provide an EVC after I am back from long weekend trip. In the meantime I think you need to remove the debug print in your commit ").

**Comment by friesencr** [comment]
It does support https.  The site only breaks in https because the assets are in http and only firefox is cranky enough to not load it.  I suspect that the problem was caused by a plugin like privacy badger on firefox but since we can support https so easily we should.  Enjoy your trip!

**Comment by weitjong** [comment]
First, I would not pretend I know a great deal about this, and to be honest I just did a quick Google search on the topic. Although I agree with you that it looks like GitHub has supported the ```https``` protocol for the *.github.io domain, they have not updated their help pages (documentation) yet which still state the pages should only be served over ```http```. As this is an undocumented feature at best, I question the time is correct to use ```https``` for our website now and the benefit of having it since we only serving mainly non-sensitive static content.

**Comment by friesencr** [comment]
The site is broken for people using https.  This is probably a case of bad documentation.  There was a big fuss around the heartbeat era and it looks like github stepped it up.  We should just merge it and test to see if the site works in https and revert it if it doesn't.

**Comment by weitjong** [comment]
Don't get me wrong. I do not actually against this, I just question on its timing and benefit. Fixing visitor with ```https``` protocol may be already a good enough excuse to make the change. However, from what I have read in my earlier search result, even with ```https``` the connection to the gh-pages only provides an illusion of trust (the meaning of green padlock is being diluted here). GitHub has officially stated that they do not offer yet end-to-end security in the gh-pages infrastructure (at some point in the connection the encryption is being removed), although the ```https``` appears to work. This is definitely not a case of bad documentation.

In my opinion, we should not rush for this. However, I won't stop you or anyone else if you want this change now. To me, the DuckDuckGo user could just simply click on any links on our website to workaround the initial ```https``` problem to get back to the ```http``` protocol. All the links in our website and external links in our forums, SourceForge.net, online documentation, README.md, etc are consistently using just ```http``` protocol. Speaking of which, if you insist on doing this change then I suppose it only makes sense if all the links are changed consistently.

I believe you have the push privilege to merge this PR yourself. About the PR, I also have one or two points about the changes you made.
- Instead of hardcoding the Disqus URL to ```https```, use the protocol-relative URL has recommended by Disqus [here](https://help.disqus.com/customer/portal/articles/542119-can-disqus-be-loaded-via-https-).
- I have followed the convention from [html5boilerplate](https://html5boilerplate.com/) when I redesigned the website last year. The ```<script>``` tag should not have ```type``` attribute in HTML5. That attribute is only mandatory in HTML4.1. So, if it is not too much of the trouble then may I request to revert back the changes on ```<script>``` tag. Thanks.

Sorry for the long post.

**Comment by friesencr** [comment]
http://www.paulirish.com/2010/the-protocol-relative-url/

At the top, the 'inventor' of the protocol url term just says to use https for all script tags.

**Comment by bentley** [comment]
As of June 8, HTTPS for GitHub Pages is no longer an undocumented feature; [it is now officially supported by GitHub](https://github.com/blog/2186-https-for-github-pages).

**Comment by weitjong** [comment]
Thanks for the link. It is time then. :smiley:

**Pull request closed without merging**
